### ISSUE TITLE
KeyError: 'x-access-token'

### ISSUE THREAD

**Issue by mikeboiko** [seansullivan44/Wealthsimple-Trade-Python#14]
I started getting this error today:
```
  File "/home/mike/.local/lib/python3.9/site-packages/wealthsimple/wealthsimple.py", line 66, in __init__
    self.login(email, password, two_factor_callback=two_factor_callback)
  File "/home/mike/.local/lib/python3.9/site-packages/wealthsimple/wealthsimple.py", line 118, in login
    {"Authorization": response.headers["X-Access-Token"]}
  File "/usr/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-access-token'
```

Not sure if wealthsimple changed their API? Anybody know how to fix it?
Thanks!

**Comment by Zechtitus** [comment]
same thing is being seen in other python wsimple api: https://github.com/yusuf8ahmed/Wsimple

I don't have time right now but I could probably look at doing a fix later next week.

**Comment by mikeboiko** [comment]
Upon doing some further investigating, I was getting this error message back:

```
Access denied

This website is using a security service to protect itself from online attacks.

    Ray ID: 62e0d849bc0af559
    Timestamp: 2021-03-11 01:00:16 UTC
    Your IP address: xxx.xx.xxx.xx
    Requested URL: trade-service.wealthsimple.com/auth/login
    Error refere nce number: 1020
    Server ID: FL_28F240
    User-Agent: python-requests/2.25.1
```
I emailed WS about it and I'll let you guys know what they say when they email me back.

**Comment by joeyorlando** [comment]
@mikeboiko was seeing the same errors recently.

Tried mimicking the requests that the web app makes when authenticating, was seeing a similar error (logically the same request with the same payload should work?):
<img width="662" alt="Screen Shot 2021-03-14 at 10 27 41 AM" src="https://user-images.githubusercontent.com/9406895/111072335-9131c280-84b0-11eb-893d-59efaa44f2de.png">


Tried this request
```
POST https://api.production.wealthsimple.com/v1/oauth/token

JSON payload: {
    "grant_type": "password",
    "username": "<email>",
    "password": "<password>",
    "skip_provision": true,
    "otp_claim": null,
    "scope": "invest.read invest.write mfda.read mfda.write mercer.read mercer.write trade.read trade.write empower.read empower.write tax.read tax.write",
    "client_id": "<pulled this from Chrome inspect when logging in via the web app>"
}

Headers
> x-wealthsimple-otp: <pulled this from my 2FA app on my phone>
> x-wealthsimple-client: wealthsimple.js
> x-ws-device-id: <pulled this from web-app login>
> user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
> origin: https://my.wealthsimple.com
> referer: https://my.wealthsimple.com/
> accept: application/json
> accept-encoding: gzip, deflate, br
> sec-fetch-mode: cors
> content-length: 410
```

There has to be a way to connect as I'm using [Wealthica](https://wealthica.com/) which pulls your portfolio in from Wealthsimple. Would be amazing to get this working as I started playing around in quant-algo trading, would love to be able to pull in my investment transactions/positions into my program.

**Comment by joeyorlando** [comment]
There seems to be a Javascript client library that solved [this issue](https://github.com/ahmedsakr/wstrade-api/issues/96). I created a fork of your repo @seansullivan44, will try to port this over to Python today

**Comment by mikeboiko** [comment]
> There seems to be a Javascript client library that solved [this issue](https://github.com/ahmedsakr/wstrade-api/issues/96). I created a fork of your repo @seansullivan44, will try to port this over to Python today

You're the man @joeyorlando!

**Comment by ahmedsakr** [comment]
I'm that JS library's maintainer. If y'all need help porting it, feel free to reach out.

**Comment by joeyorlando** [comment]
Will do! I found a similar Python version of the `cloudscraper` library you mentioned @ahmedsakr: https://github.com/venomous/cloudscraper. I believe (to be tested), that we just need to swap out `requests.Session` with an instance of `cloudscraper.CloudScraper` (which is a subclass of `requests.Session`). If it works for me I'll just open a PR against this repo instead of maintaining my own fork 🤓

**Comment by ahmedsakr** [comment]
> Will do! I found a similar Python version of the `cloudscraper` library you mentioned @ahmedsakr: https://github.com/venomous/cloudscraper. I believe (to be tested), that we just need to swap out `requests.Session` with an instance of `cloudscraper.CloudScraper` (which is a subclass of `requests.Session`). If it works for me I'll just open a PR against this repo instead of maintaining my own fork 🤓 

That's right! My changes were fairly minimal. Another python WS api library (https://github.com/yusuf8ahmed/Wsimple) is currently trying to integrate cloudscraper too. Keep in mind that it executes node code within its python modules, so you'll need to require node is available!

**Comment by joeyorlando** [comment]
PR is open, got things working!

@ahmedsakr re: your point on `node` dependency, that is correct, `cloudscraper` is dependent on `node` (see [here])(https://github.com/VeNoMouS/cloudscraper/blob/a6250bc9709574b3c034dfe3f0966afff203439e/cloudscraper/interpreters/nodejs.py#L34): 
![Screen Shot 2021-03-14 at 12 39 19 PM](https://user-images.githubusercontent.com/9406895/111076348-58024e00-84c2-11eb-98c6-ae0a42895c16.png)

I added a note to `README.rst` which states this dependency and points to the instructions on `cloudscraper`

**Comment by seansullivan44** [comment]
Thanks a bunch @joeyorlando

**Comment by joeyorlando** [comment]
no worries. you may need to manually push this to pypi? (I noticed you had a `travis.yml` file where presumably you'd do the build/push there, but it was empty)

**Comment by seansullivan44** [comment]
@joeyorlando Yes currently in the process of doing that. Was previously working on integrating with Travis but got sidetracked with school stuff. Hoping to get that set up over the next few days

**Comment by mikeboiko** [comment]
I just tested the 1.1.0 and everything works great!
Thanks again for your help @joeyorlando and @seansullivan44 
Man, I love the open source community :D
