### ISSUE TITLE
Interpreting Position codes

### ISSUE THREAD

**Issue by NicBT** [seansullivan44/Wealthsimple-Trade-Python#6]
ws.get_positions() returns security id's that are of the format "sec-c-XXX" where XXX is a 32 digit hex number. How are these meant to be interpreted? Are they wealthsimple specific or is there a database somewhere to associate them with their respective tickers?

Thank you

**Comment by seansullivan44** [comment]
I believe these are Internal Wealthsimple IDs. As of right now, I do not know a way of converting these into an associated ticker. If you find the relationships please let me know!

**Comment by NicBT** [comment]
So idk if this is new but wealthsimple has half-decent documentation for the API. In it theres reference to a "GET Security": 
https://developers.wealthsimple.com/#operation/Get%20Security.

so if you adapt your get_security function to be:
`response = self.TradeAPI.makeRequest("GET", f"securities/{security_id}")`

instead of 
`response = self.TradeAPI.makeRequest("GET", f"securities?query={symbol}")`

you'll also have to remove the `['results']` in:
`return response['results']`
since that wont actually be in the return

then wealthsimple will return a dictionary that contains all of the info listed at the link above (including the ticker)

**Comment by seansullivan44** [comment]
That documentation is actually for the Wealthsimple service, not the Wealthsimple Trade service. So, unfortunately, the majority of those endpoints don't work, but it looks like you got lucky and found one that does :) 

I will add this into change into the `get_security()` function. I will create a separate function `get_securities_from_ticker(self, symbol)` to list all securities that match a ticker symbol.
